version: "3"

includes:
  services:
    taskfile: ./services/Taskfile.yaml
    dir: ./services

tasks:
  prod-build:
    desc: "Build production images"
    cmds:
      - task: services:prod-build

  prod-up:
    desc: "Initialize Vault, provision secrets and start the production stack"
    cmds:
      - task: services:prod-up

  up:
    desc: "Alias for prod-up"
    cmds:
      - task: prod-up
