---
- name: Initialize Kubernetes Control Plane
  become: yes
  command: >
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
    --apiserver-cert-extra-sans={{ ansible_host }}
    --node-name {{ inventory_hostname }}
  register: kubeadm_init
  args:
    creates: /etc/kubernetes/admin.conf
  # On accepte si c'est déjà fait, mais on ne bloque pas la suite
  failed_when: 
    - kubeadm_init.rc != 0 
    - "'already exists' not in kubeadm_init.stderr"

- name: Create .kube directory for ubuntu user
  become: yes
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Copy admin.conf to user's kubeconfig
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: "0600"

- name: Install Helm
  become: yes
  shell: |
    set -o pipefail
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    executable: /bin/bash
    creates: /usr/local/bin/helm

- name: Deploy Cilium Networking via Helm
  become: no
  shell: |
    helm repo add cilium https://helm.cilium.io/
    helm repo update
    helm upgrade --install cilium cilium/cilium --version 1.14.5 \
      --namespace kube-system \
      --set operator.replicas=1
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  register: cilium_install
  until: cilium_install is success
  retries: 3
  delay: 10

- name: Generate cluster join command
  become: yes
  command: kubeadm token create --print-join-command
  register: join_command_raw
  changed_when: false

- name: Distribute join command to all hosts
  set_fact:
    distributed_join_command: "{{ join_command_raw.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"

- name: Create local-ready kubeconfig with public IP
  become: yes
  shell: |
    cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config_external
    PRIVATE_IP=$(hostname -I | awk '{print $1}')
    sed -i "s|$PRIVATE_IP|{{ ansible_host }}|g" /home/ubuntu/.kube/config_external
    chown ubuntu:ubuntu /home/ubuntu/.kube/config_external
  args:
    executable: /bin/bash
  tags: [always]

- name: Prepare kubeconfig for local fetch
  become: yes
  shell: |
    cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config_external
    PRIVATE_IP=$(hostname -I | awk '{print $1}')
    sed -i "s|$PRIVATE_IP|{{ ansible_host }}|g" /home/ubuntu/.kube/config_external
    chown ubuntu:ubuntu /home/ubuntu/.kube/config_external
  args:
    executable: /bin/bash
  tags: [always]

- name: Fetch kubeconfig to local machine
  become: yes
  fetch:
    src: /home/ubuntu/.kube/config_external
    dest: "{{ playbook_dir }}/../../config/kubeconfig_atfq"
    flat: yes
  tags: [always]
