apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser | default 1001 }}
        runAsNonRoot: true
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          {{- if .Values.nginxTmpEnabled }}
          volumeMounts:
            - name: nginx-tmp
              mountPath: /opt/bitnami/nginx/tmp
          {{- end }}
      volumes:
        {{- if .Values.nginxTmpEnabled }}
        - name: nginx-tmp
          emptyDir: {}
        {{- end }}
