{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "base-app.name" .) .Values.service.name }}
  labels:
{{ include "base-app.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ default .port .targetPort }}
      protocol: {{ default "TCP" .protocol }}
{{- end }}
  selector:
{{ include "base-app.selectorLabels" . | nindent 4 }}
{{- end }}
