{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "base-app.name" .) .Values.serviceAccount.name }}
  labels:
{{ include "base-app.labels" . | nindent 4 }}
{{- end }}
