volumes:
  wiki-postgres_data:
  # wiki-shared-secrets:
  #   name: vault-wiki-shared-secrets
  #   driver: local
  #   driver_opts:
  #     type: tmpfs
  #     device: tmpfs
  #     o: "size=64m,mode=770"

services:
  # SERVICE
  wiki:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    networks:
      - backend
    # volumes:
    #   - type: volume
    #     source: wiki-shared-secrets
    #     target: /vault/secrets
    #     read_only: true
    environment:
      - DATABASE_URL=postgresql://atfq:atfq@db-wiki:5432/atfq_db
      - METRICS_ADDR=0.0.0.0:9091
    # ports:
    #   - "$PORT:8080"
    depends_on:
      db-wiki:
        condition: service_healthy
      # vault-agent-wiki:
      #   condition: service_started
    restart: unless-stopped
  # ------------------------------
  # DATABASE
  db-wiki:
    image: postgres:16-alpine
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql://atfq:atfq@db-wiki:5432/atfq_db
      - POSTGRES_DB=atfq_db
      - POSTGRES_USER=atfq
      - POSTGRES_PASSWORD=atfq
      # - POSTGRES_USER_FILE=/vault/secrets/POSTGRES_USER
      # - POSTGRES_PASSWORD_FILE=/vault/secrets/POSTGRES_PASSWORD
      # - POSTGRES_DB_FILE=/vault/secrets/POSTGRES_DB
    volumes:
      - type: volume
        source: wiki-postgres_data
        target: /var/lib/postgresql/data
      # - type: volume
      #   source: wiki-shared-secrets
      #   target: /vault/secrets
      #   read_only: true
    ports:
      - "127.0.0.1:5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
  # ------------------------------
  # VAULT AGENT
  # vault-agent-wiki:
  #   image: hashicorp/vault:1.13.3
  #   container_name: vault-agent-wiki
  #   init: true
  #   networks:
  #     - backend
  #   environment:
  #     - VAULT_ADDR=http://vault:8200
  #   volumes:
  #     - type: bind
  #       source: ./vault/agent-wiki.hcl
  #       target: /etc/vault/agent-config.hcl
  #     - type: bind
  #       source: ./vault/agent_ids/role-id
  #       target: /etc/vault/role-id
  #       read_only: true
  #     - type: bind
  #       source: ./vault/agent_ids/secret-id
  #       target: /etc/vault/secret-id
  #       read_only: true
  #     - type: volume
  #       source: wiki-shared-secrets
  #       target: /vault/secrets
  #   cap_add:
  #     - IPC_LOCK
  #   restart: unless-stopped
  #   user: "root"
  #   command: >
  #     sh -c "chown -R vault:vault /vault/secrets && exec su-exec vault vault agent -config=/etc/vault/agent-config.hcl"
