services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    networks:
      - backend
      - frontend
    env_file:
      - ./.env
    # ports:
    #   - "$PORT:8080"
    restart: unless-stopped
