services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    networks:
      - backend
      - frontend
    environment:
      - STARTUP_MAX_RETRIES=90
      - JWT_SECRET=jwt_secret
      - AUTH_DATABASE_URL=postgresql://atfq:atfq@db-auth:5432/atfq_db
      - USER_DATABASE_URL=postgresql://atfq:atfq@db-user:5432/atfq_db
    restart: unless-stopped
