// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/wiki/v1/wiki.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WikiService_GetRootArticles_FullMethodName = "/wiki.WikiService/GetRootArticles"
	WikiService_CreateArticle_FullMethodName   = "/wiki.WikiService/CreateArticle"
	WikiService_CreateNode_FullMethodName      = "/wiki.WikiService/CreateNode"
	WikiService_GetArticle_FullMethodName      = "/wiki.WikiService/GetArticle"
	WikiService_UpdateNode_FullMethodName      = "/wiki.WikiService/UpdateNode"
	WikiService_DeleteNode_FullMethodName      = "/wiki.WikiService/DeleteNode"
	WikiService_AssignParent_FullMethodName    = "/wiki.WikiService/AssignParent"
	WikiService_GetHistory_FullMethodName      = "/wiki.WikiService/GetHistory"
	WikiService_GetPending_FullMethodName      = "/wiki.WikiService/GetPending"
	WikiService_GetAllPending_FullMethodName   = "/wiki.WikiService/GetAllPending"
	WikiService_ApproveVersion_FullMethodName  = "/wiki.WikiService/ApproveVersion"
	WikiService_RejectVersion_FullMethodName   = "/wiki.WikiService/RejectVersion"
	WikiService_SearchArticles_FullMethodName  = "/wiki.WikiService/SearchArticles"
)

// WikiServiceClient is the client API for WikiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WikiServiceClient interface {
	// Basic CRUD
	GetRootArticles(ctx context.Context, in *GetRootArticlesRequest, opts ...grpc.CallOption) (*GetRootArticlesResponse, error)
	CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*Article, error)
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*Node, error)
	GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*Article, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*Version, error)
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	AssignParent(ctx context.Context, in *AssignParentRequest, opts ...grpc.CallOption) (*Node, error)
	// History & Versioning
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	GetPending(ctx context.Context, in *GetPendingRequest, opts ...grpc.CallOption) (*PendingVersionsResponse, error)
	GetAllPending(ctx context.Context, in *GetAllPendingRequest, opts ...grpc.CallOption) (*PendingVersionsResponse, error)
	// Moderation
	ApproveVersion(ctx context.Context, in *ModerateVersionRequest, opts ...grpc.CallOption) (*Node, error)
	RejectVersion(ctx context.Context, in *ModerateVersionRequest, opts ...grpc.CallOption) (*Node, error)
	SearchArticles(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type wikiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWikiServiceClient(cc grpc.ClientConnInterface) WikiServiceClient {
	return &wikiServiceClient{cc}
}

func (c *wikiServiceClient) GetRootArticles(ctx context.Context, in *GetRootArticlesRequest, opts ...grpc.CallOption) (*GetRootArticlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRootArticlesResponse)
	err := c.cc.Invoke(ctx, WikiService_GetRootArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiServiceClient) CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*Article, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Article)
	err := c.cc.Invoke(ctx, WikiService_CreateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiServiceClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, WikiService_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiServiceClient) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*Article, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Article)
	err := c.cc.Invoke(ctx, WikiService_GetArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiServiceClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*Version, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Version)
	err := c.cc.Invoke(ctx, WikiService_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiServiceClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, WikiService_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiServiceClient) AssignParent(ctx context.Context, in *AssignParentRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, WikiService_AssignParent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, WikiService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiServiceClient) GetPending(ctx context.Context, in *GetPendingRequest, opts ...grpc.CallOption) (*PendingVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PendingVersionsResponse)
	err := c.cc.Invoke(ctx, WikiService_GetPending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiServiceClient) GetAllPending(ctx context.Context, in *GetAllPendingRequest, opts ...grpc.CallOption) (*PendingVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PendingVersionsResponse)
	err := c.cc.Invoke(ctx, WikiService_GetAllPending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiServiceClient) ApproveVersion(ctx context.Context, in *ModerateVersionRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, WikiService_ApproveVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiServiceClient) RejectVersion(ctx context.Context, in *ModerateVersionRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, WikiService_RejectVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiServiceClient) SearchArticles(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, WikiService_SearchArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WikiServiceServer is the server API for WikiService service.
// All implementations must embed UnimplementedWikiServiceServer
// for forward compatibility.
type WikiServiceServer interface {
	// Basic CRUD
	GetRootArticles(context.Context, *GetRootArticlesRequest) (*GetRootArticlesResponse, error)
	CreateArticle(context.Context, *CreateArticleRequest) (*Article, error)
	CreateNode(context.Context, *CreateNodeRequest) (*Node, error)
	GetArticle(context.Context, *GetArticleRequest) (*Article, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*Version, error)
	DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteResponse, error)
	AssignParent(context.Context, *AssignParentRequest) (*Node, error)
	// History & Versioning
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	GetPending(context.Context, *GetPendingRequest) (*PendingVersionsResponse, error)
	GetAllPending(context.Context, *GetAllPendingRequest) (*PendingVersionsResponse, error)
	// Moderation
	ApproveVersion(context.Context, *ModerateVersionRequest) (*Node, error)
	RejectVersion(context.Context, *ModerateVersionRequest) (*Node, error)
	SearchArticles(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedWikiServiceServer()
}

// UnimplementedWikiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWikiServiceServer struct{}

func (UnimplementedWikiServiceServer) GetRootArticles(context.Context, *GetRootArticlesRequest) (*GetRootArticlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRootArticles not implemented")
}
func (UnimplementedWikiServiceServer) CreateArticle(context.Context, *CreateArticleRequest) (*Article, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArticle not implemented")
}
func (UnimplementedWikiServiceServer) CreateNode(context.Context, *CreateNodeRequest) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedWikiServiceServer) GetArticle(context.Context, *GetArticleRequest) (*Article, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticle not implemented")
}
func (UnimplementedWikiServiceServer) UpdateNode(context.Context, *UpdateNodeRequest) (*Version, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedWikiServiceServer) DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedWikiServiceServer) AssignParent(context.Context, *AssignParentRequest) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignParent not implemented")
}
func (UnimplementedWikiServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedWikiServiceServer) GetPending(context.Context, *GetPendingRequest) (*PendingVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPending not implemented")
}
func (UnimplementedWikiServiceServer) GetAllPending(context.Context, *GetAllPendingRequest) (*PendingVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllPending not implemented")
}
func (UnimplementedWikiServiceServer) ApproveVersion(context.Context, *ModerateVersionRequest) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveVersion not implemented")
}
func (UnimplementedWikiServiceServer) RejectVersion(context.Context, *ModerateVersionRequest) (*Node, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectVersion not implemented")
}
func (UnimplementedWikiServiceServer) SearchArticles(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchArticles not implemented")
}
func (UnimplementedWikiServiceServer) mustEmbedUnimplementedWikiServiceServer() {}
func (UnimplementedWikiServiceServer) testEmbeddedByValue()                     {}

// UnsafeWikiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WikiServiceServer will
// result in compilation errors.
type UnsafeWikiServiceServer interface {
	mustEmbedUnimplementedWikiServiceServer()
}

func RegisterWikiServiceServer(s grpc.ServiceRegistrar, srv WikiServiceServer) {
	// If the following call panics, it indicates UnimplementedWikiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WikiService_ServiceDesc, srv)
}

func _WikiService_GetRootArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRootArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).GetRootArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_GetRootArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).GetRootArticles(ctx, req.(*GetRootArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiService_CreateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).CreateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_CreateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).CreateArticle(ctx, req.(*CreateArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiService_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiService_GetArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_GetArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).GetArticle(ctx, req.(*GetArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiService_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).DeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiService_AssignParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignParentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).AssignParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_AssignParent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).AssignParent(ctx, req.(*AssignParentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiService_GetPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).GetPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_GetPending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).GetPending(ctx, req.(*GetPendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiService_GetAllPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).GetAllPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_GetAllPending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).GetAllPending(ctx, req.(*GetAllPendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiService_ApproveVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModerateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).ApproveVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_ApproveVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).ApproveVersion(ctx, req.(*ModerateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiService_RejectVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModerateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).RejectVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_RejectVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).RejectVersion(ctx, req.(*ModerateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiService_SearchArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiServiceServer).SearchArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiService_SearchArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiServiceServer).SearchArticles(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WikiService_ServiceDesc is the grpc.ServiceDesc for WikiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WikiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wiki.WikiService",
	HandlerType: (*WikiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRootArticles",
			Handler:    _WikiService_GetRootArticles_Handler,
		},
		{
			MethodName: "CreateArticle",
			Handler:    _WikiService_CreateArticle_Handler,
		},
		{
			MethodName: "CreateNode",
			Handler:    _WikiService_CreateNode_Handler,
		},
		{
			MethodName: "GetArticle",
			Handler:    _WikiService_GetArticle_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _WikiService_UpdateNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _WikiService_DeleteNode_Handler,
		},
		{
			MethodName: "AssignParent",
			Handler:    _WikiService_AssignParent_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _WikiService_GetHistory_Handler,
		},
		{
			MethodName: "GetPending",
			Handler:    _WikiService_GetPending_Handler,
		},
		{
			MethodName: "GetAllPending",
			Handler:    _WikiService_GetAllPending_Handler,
		},
		{
			MethodName: "ApproveVersion",
			Handler:    _WikiService_ApproveVersion_Handler,
		},
		{
			MethodName: "RejectVersion",
			Handler:    _WikiService_RejectVersion_Handler,
		},
		{
			MethodName: "SearchArticles",
			Handler:    _WikiService_SearchArticles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/wiki/v1/wiki.proto",
}
