// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: wiki.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_TYPE_UNSPECIFIED NodeType = 0
	NodeType_TYPE_ARTICLE     NodeType = 1
	NodeType_TYPE_NOTION      NodeType = 2
	NodeType_TYPE_QUESTION    NodeType = 3
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_ARTICLE",
		2: "TYPE_NOTION",
		3: "TYPE_QUESTION",
	}
	NodeType_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_ARTICLE":     1,
		"TYPE_NOTION":      2,
		"TYPE_QUESTION":    3,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_wiki_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_wiki_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{0}
}

type Node struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId         *int32                 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Type             NodeType               `protobuf:"varint,3,opt,name=type,proto3,enum=wiki.NodeType" json:"type,omitempty"`
	CurrentVersionId int32                  `protobuf:"varint,4,opt,name=current_version_id,json=currentVersionId,proto3" json:"current_version_id,omitempty"`
	OrderIndex       int32                  `protobuf:"varint,5,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	// Data from the current version
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Author        int32                  `protobuf:"varint,9,opt,name=author,proto3" json:"author,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,10,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_wiki_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetParentId() int32 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *Node) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_TYPE_UNSPECIFIED
}

func (x *Node) GetCurrentVersionId() int32 {
	if x != nil {
		return x.CurrentVersionId
	}
	return 0
}

func (x *Node) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *Node) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Node) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Node) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Node) GetAuthor() int32 {
	if x != nil {
		return x.Author
	}
	return 0
}

func (x *Node) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     int32                  `protobuf:"varint,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // pending, approved, rejected, archived
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Author        int32                  `protobuf:"varint,7,opt,name=author,proto3" json:"author,omitempty"`
	ActivatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=activated_at,json=activatedAt,proto3,oneof" json:"activated_at,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"` // Only populated if type is question
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_wiki_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{1}
}

func (x *Version) GetVersionId() int32 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *Version) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Version) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Version) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Version) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Version) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Version) GetAuthor() int32 {
	if x != nil {
		return x.Author
	}
	return 0
}

func (x *Version) GetActivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActivatedAt
	}
	return nil
}

func (x *Version) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type NodeBreadcrumb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeBreadcrumb) Reset() {
	*x = NodeBreadcrumb{}
	mi := &file_wiki_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeBreadcrumb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeBreadcrumb) ProtoMessage() {}

func (x *NodeBreadcrumb) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeBreadcrumb.ProtoReflect.Descriptor instead.
func (*NodeBreadcrumb) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{2}
}

func (x *NodeBreadcrumb) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeBreadcrumb) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleNode   *Node                  `protobuf:"bytes,1,opt,name=article_node,json=articleNode,proto3" json:"article_node,omitempty"`
	SubArticles   []*NodeBreadcrumb      `protobuf:"bytes,2,rep,name=sub_articles,json=subArticles,proto3" json:"sub_articles,omitempty"`
	Notions       []*Node                `protobuf:"bytes,3,rep,name=notions,proto3" json:"notions,omitempty"`
	Questions     []*Node                `protobuf:"bytes,4,rep,name=questions,proto3" json:"questions,omitempty"`
	Lineage       []*NodeBreadcrumb      `protobuf:"bytes,5,rep,name=lineage,proto3" json:"lineage,omitempty"`           // Parent hierarchy (Breadcrumbs)
	Contributors  []string               `protobuf:"bytes,6,rep,name=contributors,proto3" json:"contributors,omitempty"` // List of authors from versions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_wiki_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{3}
}

func (x *Article) GetArticleNode() *Node {
	if x != nil {
		return x.ArticleNode
	}
	return nil
}

func (x *Article) GetSubArticles() []*NodeBreadcrumb {
	if x != nil {
		return x.SubArticles
	}
	return nil
}

func (x *Article) GetNotions() []*Node {
	if x != nil {
		return x.Notions
	}
	return nil
}

func (x *Article) GetQuestions() []*Node {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *Article) GetLineage() []*NodeBreadcrumb {
	if x != nil {
		return x.Lineage
	}
	return nil
}

func (x *Article) GetContributors() []string {
	if x != nil {
		return x.Contributors
	}
	return nil
}

type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      *int32                 `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Type          NodeType               `protobuf:"varint,2,opt,name=type,proto3,enum=wiki.NodeType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	OrderIndex    int32                  `protobuf:"varint,5,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"` // Used if type is Question
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_wiki_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{4}
}

func (x *CreateNodeRequest) GetParentId() int32 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *CreateNodeRequest) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_TYPE_UNSPECIFIED
}

func (x *CreateNodeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNodeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateNodeRequest) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *CreateNodeRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleNode   *CreateNodeRequest     `protobuf:"bytes,1,opt,name=article_node,json=articleNode,proto3" json:"article_node,omitempty"`
	Children      []*CreateNodeRequest   `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_wiki_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{5}
}

func (x *CreateArticleRequest) GetArticleNode() *CreateNodeRequest {
	if x != nil {
		return x.ArticleNode
	}
	return nil
}

func (x *CreateArticleRequest) GetChildren() []*CreateNodeRequest {
	if x != nil {
		return x.Children
	}
	return nil
}

type UpdateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`     // Optional: send new title
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // Optional: send new content
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeRequest) Reset() {
	*x = UpdateNodeRequest{}
	mi := &file_wiki_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeRequest) ProtoMessage() {}

func (x *UpdateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateNodeRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *UpdateNodeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNodeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateNodeRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_wiki_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{7}
}

func (x *GetArticleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_wiki_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{8}
}

func (x *GetHistoryRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*Version             `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_wiki_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{9}
}

func (x *GetHistoryResponse) GetVersions() []*Version {
	if x != nil {
		return x.Versions
	}
	return nil
}

type GetPendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingRequest) Reset() {
	*x = GetPendingRequest{}
	mi := &file_wiki_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingRequest) ProtoMessage() {}

func (x *GetPendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingRequest.ProtoReflect.Descriptor instead.
func (*GetPendingRequest) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{10}
}

func (x *GetPendingRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type GetAllPendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPendingRequest) Reset() {
	*x = GetAllPendingRequest{}
	mi := &file_wiki_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPendingRequest) ProtoMessage() {}

func (x *GetAllPendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPendingRequest.ProtoReflect.Descriptor instead.
func (*GetAllPendingRequest) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{11}
}

type PendingVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*Version             `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingVersionsResponse) Reset() {
	*x = PendingVersionsResponse{}
	mi := &file_wiki_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingVersionsResponse) ProtoMessage() {}

func (x *PendingVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingVersionsResponse.ProtoReflect.Descriptor instead.
func (*PendingVersionsResponse) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{12}
}

func (x *PendingVersionsResponse) GetVersions() []*Version {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ModerateVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     int32                  `protobuf:"varint,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModerateVersionRequest) Reset() {
	*x = ModerateVersionRequest{}
	mi := &file_wiki_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerateVersionRequest) ProtoMessage() {}

func (x *ModerateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerateVersionRequest.ProtoReflect.Descriptor instead.
func (*ModerateVersionRequest) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{13}
}

func (x *ModerateVersionRequest) GetVersionId() int32 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_wiki_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteNodeRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type GetRootArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootArticlesRequest) Reset() {
	*x = GetRootArticlesRequest{}
	mi := &file_wiki_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootArticlesRequest) ProtoMessage() {}

func (x *GetRootArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetRootArticlesRequest) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{15}
}

type GetRootArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*NodeBreadcrumb      `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootArticlesResponse) Reset() {
	*x = GetRootArticlesResponse{}
	mi := &file_wiki_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootArticlesResponse) ProtoMessage() {}

func (x *GetRootArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetRootArticlesResponse) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{16}
}

func (x *GetRootArticlesResponse) GetArticles() []*NodeBreadcrumb {
	if x != nil {
		return x.Articles
	}
	return nil
}

type AssignParentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewParent     int32                  `protobuf:"varint,1,opt,name=new_parent,json=newParent,proto3" json:"new_parent,omitempty"`
	Child         int32                  `protobuf:"varint,2,opt,name=child,proto3" json:"child,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignParentRequest) Reset() {
	*x = AssignParentRequest{}
	mi := &file_wiki_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignParentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignParentRequest) ProtoMessage() {}

func (x *AssignParentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignParentRequest.ProtoReflect.Descriptor instead.
func (*AssignParentRequest) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{17}
}

func (x *AssignParentRequest) GetNewParent() int32 {
	if x != nil {
		return x.NewParent
	}
	return 0
}

func (x *AssignParentRequest) GetChild() int32 {
	if x != nil {
		return x.Child
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_wiki_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{18}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*NodeBreadcrumb      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_wiki_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_wiki_proto_rawDescGZIP(), []int{19}
}

func (x *SearchResponse) GetResults() []*NodeBreadcrumb {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_wiki_proto protoreflect.FileDescriptor

const file_wiki_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"wiki.proto\x12\x04wiki\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x83\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12 \n" +
	"\tparent_id\x18\x02 \x01(\x05H\x00R\bparentId\x88\x01\x01\x12\"\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0e.wiki.NodeTypeR\x04type\x12,\n" +
	"\x12current_version_id\x18\x04 \x01(\x05R\x10currentVersionId\x12\x1f\n" +
	"\vorder_index\x18\x05 \x01(\x05R\n" +
	"orderIndex\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06author\x18\t \x01(\x05R\x06author\x128\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructH\x01R\bmetadata\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\v\n" +
	"\t_metadata\"\xe6\x02\n" +
	"\aVersion\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\x05R\tversionId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06author\x18\a \x01(\x05R\x06author\x12B\n" +
	"\factivated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vactivatedAt\x88\x01\x01\x123\n" +
	"\bmetadata\x18\t \x01(\v2\x17.google.protobuf.StructR\bmetadataB\x0f\n" +
	"\r_activated_at\"6\n" +
	"\x0eNodeBreadcrumb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x95\x02\n" +
	"\aArticle\x12-\n" +
	"\farticle_node\x18\x01 \x01(\v2\n" +
	".wiki.NodeR\varticleNode\x127\n" +
	"\fsub_articles\x18\x02 \x03(\v2\x14.wiki.NodeBreadcrumbR\vsubArticles\x12$\n" +
	"\anotions\x18\x03 \x03(\v2\n" +
	".wiki.NodeR\anotions\x12(\n" +
	"\tquestions\x18\x04 \x03(\v2\n" +
	".wiki.NodeR\tquestions\x12.\n" +
	"\alineage\x18\x05 \x03(\v2\x14.wiki.NodeBreadcrumbR\alineage\x12\"\n" +
	"\fcontributors\x18\x06 \x03(\tR\fcontributors\"\xed\x01\n" +
	"\x11CreateNodeRequest\x12 \n" +
	"\tparent_id\x18\x01 \x01(\x05H\x00R\bparentId\x88\x01\x01\x12\"\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0e.wiki.NodeTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1f\n" +
	"\vorder_index\x18\x05 \x01(\x05R\n" +
	"orderIndex\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadataB\f\n" +
	"\n" +
	"_parent_id\"\x87\x01\n" +
	"\x14CreateArticleRequest\x12:\n" +
	"\farticle_node\x18\x01 \x01(\v2\x17.wiki.CreateNodeRequestR\varticleNode\x123\n" +
	"\bchildren\x18\x02 \x03(\v2\x17.wiki.CreateNodeRequestR\bchildren\"\x91\x01\n" +
	"\x11UpdateNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\",\n" +
	"\x11GetHistoryRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\"?\n" +
	"\x12GetHistoryResponse\x12)\n" +
	"\bversions\x18\x01 \x03(\v2\r.wiki.VersionR\bversions\",\n" +
	"\x11GetPendingRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\"\x16\n" +
	"\x14GetAllPendingRequest\"D\n" +
	"\x17PendingVersionsResponse\x12)\n" +
	"\bversions\x18\x01 \x03(\v2\r.wiki.VersionR\bversions\"7\n" +
	"\x16ModerateVersionRequest\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\x05R\tversionId\",\n" +
	"\x11DeleteNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\"\x18\n" +
	"\x16GetRootArticlesRequest\"K\n" +
	"\x17GetRootArticlesResponse\x120\n" +
	"\barticles\x18\x01 \x03(\v2\x14.wiki.NodeBreadcrumbR\barticles\"J\n" +
	"\x13AssignParentRequest\x12\x1d\n" +
	"\n" +
	"new_parent\x18\x01 \x01(\x05R\tnewParent\x12\x14\n" +
	"\x05child\x18\x02 \x01(\x05R\x05child\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"@\n" +
	"\x0eSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.wiki.NodeBreadcrumbR\aresults*V\n" +
	"\bNodeType\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTYPE_ARTICLE\x10\x01\x12\x0f\n" +
	"\vTYPE_NOTION\x10\x02\x12\x11\n" +
	"\rTYPE_QUESTION\x10\x032\xaa\x06\n" +
	"\vWikiService\x12N\n" +
	"\x0fGetRootArticles\x12\x1c.wiki.GetRootArticlesRequest\x1a\x1d.wiki.GetRootArticlesResponse\x12:\n" +
	"\rCreateArticle\x12\x1a.wiki.CreateArticleRequest\x1a\r.wiki.Article\x121\n" +
	"\n" +
	"CreateNode\x12\x17.wiki.CreateNodeRequest\x1a\n" +
	".wiki.Node\x124\n" +
	"\n" +
	"GetArticle\x12\x17.wiki.GetArticleRequest\x1a\r.wiki.Article\x124\n" +
	"\n" +
	"UpdateNode\x12\x17.wiki.UpdateNodeRequest\x1a\r.wiki.Version\x121\n" +
	"\n" +
	"DeleteNode\x12\x17.wiki.DeleteNodeRequest\x1a\n" +
	".wiki.Node\x125\n" +
	"\fAssignParent\x12\x19.wiki.AssignParentRequest\x1a\n" +
	".wiki.Node\x12?\n" +
	"\n" +
	"GetHistory\x12\x17.wiki.GetHistoryRequest\x1a\x18.wiki.GetHistoryResponse\x12D\n" +
	"\n" +
	"GetPending\x12\x17.wiki.GetPendingRequest\x1a\x1d.wiki.PendingVersionsResponse\x12J\n" +
	"\rGetAllPending\x12\x1a.wiki.GetAllPendingRequest\x1a\x1d.wiki.PendingVersionsResponse\x12:\n" +
	"\x0eApproveVersion\x12\x1c.wiki.ModerateVersionRequest\x1a\n" +
	".wiki.Node\x12:\n" +
	"\vDenyVersion\x12\x1c.wiki.ModerateVersionRequest\x1a\r.wiki.Version\x12;\n" +
	"\x0eSearchArticles\x12\x13.wiki.SearchRequest\x1a\x14.wiki.SearchResponseB\x14Z\x12wiki/proto/wiki/v1b\x06proto3"

var (
	file_wiki_proto_rawDescOnce sync.Once
	file_wiki_proto_rawDescData []byte
)

func file_wiki_proto_rawDescGZIP() []byte {
	file_wiki_proto_rawDescOnce.Do(func() {
		file_wiki_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wiki_proto_rawDesc), len(file_wiki_proto_rawDesc)))
	})
	return file_wiki_proto_rawDescData
}

var file_wiki_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wiki_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_wiki_proto_goTypes = []any{
	(NodeType)(0),                   // 0: wiki.NodeType
	(*Node)(nil),                    // 1: wiki.Node
	(*Version)(nil),                 // 2: wiki.Version
	(*NodeBreadcrumb)(nil),          // 3: wiki.NodeBreadcrumb
	(*Article)(nil),                 // 4: wiki.Article
	(*CreateNodeRequest)(nil),       // 5: wiki.CreateNodeRequest
	(*CreateArticleRequest)(nil),    // 6: wiki.CreateArticleRequest
	(*UpdateNodeRequest)(nil),       // 7: wiki.UpdateNodeRequest
	(*GetArticleRequest)(nil),       // 8: wiki.GetArticleRequest
	(*GetHistoryRequest)(nil),       // 9: wiki.GetHistoryRequest
	(*GetHistoryResponse)(nil),      // 10: wiki.GetHistoryResponse
	(*GetPendingRequest)(nil),       // 11: wiki.GetPendingRequest
	(*GetAllPendingRequest)(nil),    // 12: wiki.GetAllPendingRequest
	(*PendingVersionsResponse)(nil), // 13: wiki.PendingVersionsResponse
	(*ModerateVersionRequest)(nil),  // 14: wiki.ModerateVersionRequest
	(*DeleteNodeRequest)(nil),       // 15: wiki.DeleteNodeRequest
	(*GetRootArticlesRequest)(nil),  // 16: wiki.GetRootArticlesRequest
	(*GetRootArticlesResponse)(nil), // 17: wiki.GetRootArticlesResponse
	(*AssignParentRequest)(nil),     // 18: wiki.AssignParentRequest
	(*SearchRequest)(nil),           // 19: wiki.SearchRequest
	(*SearchResponse)(nil),          // 20: wiki.SearchResponse
	(*timestamppb.Timestamp)(nil),   // 21: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 22: google.protobuf.Struct
}
var file_wiki_proto_depIdxs = []int32{
	0,  // 0: wiki.Node.type:type_name -> wiki.NodeType
	21, // 1: wiki.Node.created_at:type_name -> google.protobuf.Timestamp
	22, // 2: wiki.Node.metadata:type_name -> google.protobuf.Struct
	21, // 3: wiki.Version.created_at:type_name -> google.protobuf.Timestamp
	21, // 4: wiki.Version.activated_at:type_name -> google.protobuf.Timestamp
	22, // 5: wiki.Version.metadata:type_name -> google.protobuf.Struct
	1,  // 6: wiki.Article.article_node:type_name -> wiki.Node
	3,  // 7: wiki.Article.sub_articles:type_name -> wiki.NodeBreadcrumb
	1,  // 8: wiki.Article.notions:type_name -> wiki.Node
	1,  // 9: wiki.Article.questions:type_name -> wiki.Node
	3,  // 10: wiki.Article.lineage:type_name -> wiki.NodeBreadcrumb
	0,  // 11: wiki.CreateNodeRequest.type:type_name -> wiki.NodeType
	22, // 12: wiki.CreateNodeRequest.metadata:type_name -> google.protobuf.Struct
	5,  // 13: wiki.CreateArticleRequest.article_node:type_name -> wiki.CreateNodeRequest
	5,  // 14: wiki.CreateArticleRequest.children:type_name -> wiki.CreateNodeRequest
	22, // 15: wiki.UpdateNodeRequest.metadata:type_name -> google.protobuf.Struct
	2,  // 16: wiki.GetHistoryResponse.versions:type_name -> wiki.Version
	2,  // 17: wiki.PendingVersionsResponse.versions:type_name -> wiki.Version
	3,  // 18: wiki.GetRootArticlesResponse.articles:type_name -> wiki.NodeBreadcrumb
	3,  // 19: wiki.SearchResponse.results:type_name -> wiki.NodeBreadcrumb
	16, // 20: wiki.WikiService.GetRootArticles:input_type -> wiki.GetRootArticlesRequest
	6,  // 21: wiki.WikiService.CreateArticle:input_type -> wiki.CreateArticleRequest
	5,  // 22: wiki.WikiService.CreateNode:input_type -> wiki.CreateNodeRequest
	8,  // 23: wiki.WikiService.GetArticle:input_type -> wiki.GetArticleRequest
	7,  // 24: wiki.WikiService.UpdateNode:input_type -> wiki.UpdateNodeRequest
	15, // 25: wiki.WikiService.DeleteNode:input_type -> wiki.DeleteNodeRequest
	18, // 26: wiki.WikiService.AssignParent:input_type -> wiki.AssignParentRequest
	9,  // 27: wiki.WikiService.GetHistory:input_type -> wiki.GetHistoryRequest
	11, // 28: wiki.WikiService.GetPending:input_type -> wiki.GetPendingRequest
	12, // 29: wiki.WikiService.GetAllPending:input_type -> wiki.GetAllPendingRequest
	14, // 30: wiki.WikiService.ApproveVersion:input_type -> wiki.ModerateVersionRequest
	14, // 31: wiki.WikiService.DenyVersion:input_type -> wiki.ModerateVersionRequest
	19, // 32: wiki.WikiService.SearchArticles:input_type -> wiki.SearchRequest
	17, // 33: wiki.WikiService.GetRootArticles:output_type -> wiki.GetRootArticlesResponse
	4,  // 34: wiki.WikiService.CreateArticle:output_type -> wiki.Article
	1,  // 35: wiki.WikiService.CreateNode:output_type -> wiki.Node
	4,  // 36: wiki.WikiService.GetArticle:output_type -> wiki.Article
	2,  // 37: wiki.WikiService.UpdateNode:output_type -> wiki.Version
	1,  // 38: wiki.WikiService.DeleteNode:output_type -> wiki.Node
	1,  // 39: wiki.WikiService.AssignParent:output_type -> wiki.Node
	10, // 40: wiki.WikiService.GetHistory:output_type -> wiki.GetHistoryResponse
	13, // 41: wiki.WikiService.GetPending:output_type -> wiki.PendingVersionsResponse
	13, // 42: wiki.WikiService.GetAllPending:output_type -> wiki.PendingVersionsResponse
	1,  // 43: wiki.WikiService.ApproveVersion:output_type -> wiki.Node
	2,  // 44: wiki.WikiService.DenyVersion:output_type -> wiki.Version
	20, // 45: wiki.WikiService.SearchArticles:output_type -> wiki.SearchResponse
	33, // [33:46] is the sub-list for method output_type
	20, // [20:33] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_wiki_proto_init() }
func file_wiki_proto_init() {
	if File_wiki_proto != nil {
		return
	}
	file_wiki_proto_msgTypes[0].OneofWrappers = []any{}
	file_wiki_proto_msgTypes[1].OneofWrappers = []any{}
	file_wiki_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wiki_proto_rawDesc), len(file_wiki_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wiki_proto_goTypes,
		DependencyIndexes: file_wiki_proto_depIdxs,
		EnumInfos:         file_wiki_proto_enumTypes,
		MessageInfos:      file_wiki_proto_msgTypes,
	}.Build()
	File_wiki_proto = out.File
	file_wiki_proto_goTypes = nil
	file_wiki_proto_depIdxs = nil
}
