volumes:
  user-postgres_data:
  user-minio_data:
  # user-shared-secrets:
  #   name: vault-user-shared-secrets
  #   driver: local
  #   driver_opts:
  #     type: tmpfs
  #     device: tmpfs
  #     o: "size=64m,mode=770"

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    networks:
      - backend
    # volumes:
    #   - type: volume
    #     source: user-shared-secrets
    #     target: /vault/secrets
    #     read_only: true
    environment:
      - DATABASE_URL=postgresql://atfq:atfq@db-user:5432/atfq_db
      - SERVER_ADDR=0.0.0.0:8080
      - METRICS_ADDR=0.0.0.0:9091
      - JWT_SECRET=jwt_secret
      - S3_ENDPOINT=http://minio-user:9000
      - S3_PUBLIC_URL=http://localhost:9000
      - S3_BUCKET=profiles
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    depends_on:
      db-user:
        condition: service_started
      minio:
        condition: service_started
      create-buckets:
        condition: service_completed_successfully
      # vault-agent-user:
      #   condition: service_started
    restart: unless-stopped
    ports:
      - "8083:8080"
  # ------------------------------
  db-user:
    image: postgres:16-alpine
    container_name: db-user
    networks:
      - backend
    environment:
      - POSTGRES_DB=atfq_db
      - POSTGRES_USER=atfq
      - POSTGRES_PASSWORD=atfq
      # - POSTGRES_USER_FILE=/vault/secrets/POSTGRES_USER
      # - POSTGRES_PASSWORD_FILE=/vault/secrets/POSTGRES_PASSWORD
      # - POSTGRES_DB_FILE=/vault/secrets/POSTGRES_DB
    volumes:
      - type: volume
        source: user-postgres_data
        target: /var/lib/postgresql/data
      # - type: volume
      #   source: user-shared-secrets
      #   target: /vault/secrets
      #   read_only: true
    ports:
      - "127.0.0.1:5433:5432"
    command: >
      sh -c "exec docker-entrypoint.sh postgres"

  # ------------------------------
  minio:
    image: minio/minio
    container_name: minio-user
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Interface Web (Console)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      # MINIO_ROOT_USER_FILE: /vault/secrets/MINIO_ROOT_USER
      # MINIO_ROOT_PASSWORD_FILE: /vault/secrets/MINIO_ROOT_PASSWORD
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    volumes:
      - type: volume
        source: user-minio_data
        target: /data
      # - type: volume
      #   source: user-shared-secrets
      #   target: /vault/secrets
      #   read_only: true
    networks:
      - backend
    command: server /data --console-address ":9001"
    restart: unless-stopped

  # Service utilitaire pour créer le bucket automatiquement
  create-buckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - backend
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...';
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/profiles || echo 'Bucket already exists';
      /usr/bin/mc anonymous set public myminio/profiles;
      echo 'Buckets created successfully';
      exit 0;
      "
  # ------------------------------
  # VAULT AGENT
  # vault-agent-user:
  #   image: hashicorp/vault:1.13.3
  #   container_name: vault-agent-user
  #   init: true
  #   networks:
  #     - backend
  #   environment:
  #     - VAULT_ADDR=http://vault:8200
  #   volumes:
  #     - type: bind
  #       source: ./vault/agent-user.hcl
  #       target: /etc/vault/agent-config.hcl
  #     - type: bind
  #       source: ./vault/agent_ids/role-id
  #       target: /etc/vault/role-id
  #       read_only: true
  #     - type: bind
  #       source: ./vault/agent_ids/secret-id
  #       target: /etc/vault/secret-id
  #       read_only: true
  #     - type: volume
  #       source: user-shared-secrets
  #       target: /vault/secrets
  #   cap_add:
  #     - IPC_LOCK
  #   restart: unless-stopped
  #   user: "root"
  #   command: >
  #     sh -c "chown -R vault:vault /vault/secrets && exec su-exec vault vault agent -config=/etc/vault/agent-config.hcl"
