volumes:
  user-postgres_data:
  user-minio_data:

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql://atfq:atfq@db-user:5432/atfq_db
      - SERVER_ADDR=0.0.0.0:8080
      - METRICS_ADDR=0.0.0.0:9091
      - JWT_SECRET=jwt_secret
      - S3_ENDPOINT=http://minio-user:9000
      - S3_PUBLIC_URL=http://localhost:9000
      - S3_BUCKET=profiles
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    depends_on:
      db-user:
        condition: service_started
      minio:
        condition: service_started
      create-buckets:
        condition: service_completed_successfully
    restart: unless-stopped
    ports:
      - "8083:8080"
  # ------------------------------
  db-user:
    image: postgres:16-alpine
    container_name: db-user
    networks:
      - backend
    environment:
      - POSTGRES_DB=atfq_db
      - POSTGRES_USER=atfq
      - POSTGRES_PASSWORD=atfq
    volumes:
      - type: volume
        source: user-postgres_data
        target: /var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    command: >
      sh -c "exec docker-entrypoint.sh postgres"

  # ------------------------------
  minio:
    image: minio/minio
    container_name: minio-user
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Interface Web (Console)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    volumes:
      - type: volume
        source: user-minio_data
        target: /data
    networks:
      - backend
    command: server /data --console-address ":9001"
    restart: unless-stopped

  # Service utilitaire pour créer le bucket automatiquement
  create-buckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - backend
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...';
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/profiles || echo 'Bucket already exists';
      /usr/bin/mc anonymous set public myminio/profiles;
      echo 'Buckets created successfully';
      exit 0;
      "
