services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    networks:
      - frontend
    restart: unless-stopped
    environment:
      - VITE_ENABLE_MOCKS=false
      - VITE_API_URL=/api/v1
