server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location /ping {
          access_log off;
          add_header 'Content-Type' 'text/plain';
          return 200 "pong";
    }

    location / {
        # Redirect all 404s to index.html for React Router
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets - Optimized Performance
    # This block inherits the 'root' from the server level
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
        # Disable access logs for static assets to reduce I/O load
        access_log off;
    }

    # Custom error pages
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        # Also inherits the root
    }
}
