include:
  - ./api-gateway/docker-compose.yaml
  - ./app/docker-compose.yaml
  - ./auth/docker-compose.yaml
  - ./net-gateway/docker-compose.yaml
  - ./user/docker-compose.yaml
  - ./wiki/docker-compose.yaml
  - ./vault/docker-compose.yaml
  # - ./monitoring/docker-compose.yaml

networks:
  frontend:
    name: atfq_frontend
    driver: bridge
  backend:
    name: atfq_backend
    driver: bridge
