services:
  net-gateway:
    restart: always
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    # healthcheck:
  api-gateway:
    build:
      target: prod
    restart: always
    volumes: []
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    # healthcheck:
  app:
    build:
      target: prod
    restart: always
    volumes: []
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    # healthcheck:
  auth:
    build:
      target: prod
    restart: always
    volumes: []
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    # healthcheck:
  user:
    build:
      target: prod
    restart: always
    volumes: []
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    # healthcheck:
  wiki:
    build:
      target: prod
    restart: always
    volumes: []
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    # healthcheck:
    #   test: ["./healthcheck"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
