volumes:
  cargo-cache:
  auth-target-cache:
  api-gateway-target-cache:

services:
  api-gateway:
    # profiles: ["dev"]
    build:
      target: dev
    ports:
      - "8081:8080"
    volumes:
      # Hot Reload
      - type: bind
        source: ./api-gateway
        target: /app
        consistency: cached
      - type: bind
        source: ./auth/proto/auth
        target: /app/proto/auth
      - type: bind
        source: ./user/proto/user
        target: /app/proto/user
      # Cargo cache
      - type: volume
        source: cargo-cache
        target: /usr/local/cargo/registry
      # Prevent re-compilation
      - type: volume
        source: api-gateway-target-cache
        target: /app/target
    # depends_on:
    #   - auth
  app:
    # profiles: ["dev"]
    build:
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: volume
        target: /app/node_modules
    # depends_on:
    #   - api-gateway
  auth:
    # profiles: ["dev"]
    build:
      target: dev
    ports:
      - "8082:8080"
    volumes:
      - type: bind
        source: ./auth
        target: /app
        consistency: cached
      - type: volume
        source: cargo-cache
        target: /usr/local/cargo/registry
      - type: volume
        source: auth-target-cache
        target: /app/target
  # net-gateway:
  # profiles: ["dev"]
  user:
    # profiles: ["full"]
    build:
      target: dev
    ports:
      - "8083:8080"
    volumes:
      - type: bind
        source: ./user
        target: /app
        consistency: cached
      - type: volume
        target: /app/node_modules
  # db-user:
  # profiles: ["full"]
  wiki:
    # profiles: ["full"]
    build:
      target: dev
    ports:
      - "8084:8080"
    volumes:
      - type: bind
        source: ./wiki
        target: /app
        consistency: cached
  # db-wiki:
  # profiles: ["full"]
  # vault:
  # profiles: ["dev"]
