version: "3"

vars:
  COMPOSE_PROD: -f docker-compose.yaml -f docker-compose.prod.yaml
  GH_USER: "moha-bekh"
  REGISTRY: ghcr.io
  VERSION: '{{.VERSION | default "latest"}}'
  TARGET: '{{.TARGET | default "prod"}}'

includes:
  auth:
    taskfile: ./auth/Taskfile.yaml
    dir: ./auth
  vault:
    taskfile: ./vault/Taskfile.yaml
    dir: ./vault

  docker:
    taskfile: ./tasks/Taskcompose.yaml
    aliases: [dc]
  img:
    taskfile: ./tasks/Taskregistry.yaml

tasks:
  list-files:
    desc: "List project files excluding noise"
    cmds:
      - (cd {{.CLI_ARGS}} && tree -I "target|node_modules|.git|.cargo-ok|.step")

  auth-up:
    cmds:
      - task dc:up -- auth -d
      - sleep 5
      - task auth:migrate-run
      - task auth:offline-prepare
      - task dc:up -- api-gateway app net-gateway -d
