version: "3"

vars:
  COMPOSE_PROD: -f docker-compose.yaml -f docker-compose.prod.yaml
  GH_USER: "moha-bekh"
  REGISTRY: ghcr.io
  VERSION: '{{.VERSION | default "latest"}}'
  TARGET: '{{.TARGET | default "prod"}}'

includes:
  auth:
    taskfile: ./auth/Taskfile.yaml
    dir: ./auth
  app:
    taskfile: ./app/Taskfile.yaml
    dir: ./app
  user:
    taskfile: ./user/Taskfile.yaml
    dir: ./user
  wiki:
    taskfile: ./wiki/Taskfile.yaml
    dir: ./wiki
  net-gateway:
    taskfile: ./net-gateway/Taskfile.yaml
    dir: ./net-gateway
  vault:
    taskfile: ./vault/Taskfile.yaml
    dir: ./vault
  prod:
    taskfile: ./Taskprod.yaml

  docker:
    taskfile: ./tasks/Taskcompose.yaml
    aliases: [dc]
  img:
    taskfile: ./tasks/Taskregistry.yaml

tasks:
  prod-build:
    desc: "Build production images"
    cmds:
      - task dc:prod-build

  prod-up:
    desc: "Initialize Vault, provision secrets and start the production stack"
    cmds:
      - task dc:prod

  up:
    desc: "Build images, then start the production stack"
    cmds:
      - task: prod-build
      - task: prod-up

  re:
    desc: "Clean all local infra data, build images, then start the production stack"
    cmds:
      - task dc:clean
      - task: up
