version: "3"

tasks:
  setup:
    desc: "Provision Vault for Auth service"
    cmds:
      # 1. Write Policy
      - docker exec -e VAULT_TOKEN=$VAULT_TOKEN -i vault vault policy write auth-service - < ./policy.hcl
      
      # 2. Configure AppRole
      - docker exec -e VAULT_TOKEN=$VAULT_TOKEN -i vault vault write auth/approle/role/auth-service - < ./role.json
      
      # 3. Inject Secrets
      - |
        docker exec -e VAULT_TOKEN=$VAULT_TOKEN vault vault kv put secret/auth \
          db_url="$AUTH_DB_URL" \
          db_name="$AUTH_DB_NAME" \
          db_user="$AUTH_DB_USER" \
          db_password="$AUTH_DB_PASSWORD" \
          server_addr="$AUTH_SERVER_ADDR" \
          jwt_secret="$AUTH_JWT" \
          cha_cha_key="$AUTH_CHA_CHA_KEY" \
          google_client_id="$AUTH_GOOGLE_CLIENT_ID" \
          google_client_secret="$AUTH_GOOGLE_CLIENT_SECRET" \
          google_redirect_url="$AUTH_GOOGLE_REDIRECT_URL" \
          github_client_id="$AUTH_GITHUB_CLIENT_ID" \
          github_client_secret="$AUTH_GITHUB_CLIENT_SECRET" \
          github_redirect_url="$AUTH_GITHUB_REDIRECT_URL" \
          smtp_username="$AUTH_SMTP_USERNAME" \
          smtp_password="$AUTH_SMTP_PASSWORD"
          
      # 4. Generate IDs for the app
      - mkdir -p ../../../auth/vault/agent_ids/
      - docker exec -e VAULT_TOKEN=$VAULT_TOKEN vault vault read -field=role_id auth/approle/role/auth-service/role-id > ../../../auth/vault/agent_ids/role-id
      - docker exec -e VAULT_TOKEN=$VAULT_TOKEN vault vault write -f -field=secret_id auth/approle/role/auth-service/secret-id > ../../../auth/vault/agent_ids/secret-id
