repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:

  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    values:
      - controller:
          admissionWebhooks:
            enabled: false
          kind: DaemonSet
          hostNetwork: true
          service:
            type: ClusterIP
          nodeSelector:
            type: workload

  - name: app-nginx
    chart: ../../services/app-nginx
