load_module modules/ngx_http_modsecurity_module.so;
load_module modules/ngx_http_headers_more_filter_module.so;

pid /tmp/nginx.pid;

worker_processes auto;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    include /etc/nginx/conf.d/*.conf;

    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 10m;
    gzip on;

    upstream app { server app:8080; }
    upstream api_gateway { server api-gateway:8080; }

    server {
        listen 80;
        server_name atfq.org www.atfq.org;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
      listen 443 ssl;
      server_name atfq.org www.atfq.org;

      ssl_certificate /app/secrets/ssl.crt;
      ssl_certificate_key /app/secrets/ssl.key;

      location ^~ /auth/callback/ {
        modsecurity off;
        proxy_pass http://app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /api/ {
        proxy_pass http://api_gateway;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location / {
        proxy_pass http://app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
}
