worker_processes auto;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    
    sendfile on;
    keepalive_timeout 65;
    gzip on;

    upstream app { server app:8080; }
    upstream api_gateway { server api-gateway:8080; }
    upstream auth_api { server auth:8080; }
    upstream user_api { server user:8080; }
    upstream wiki_api { server wiki:8080; }

    # --- HTTP: Redirect to HTTPS or handle Certbot ---
    server {
        listen 80;
        server_name localhost; # Replace with atfq.org later

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # For now, we don't redirect to 443 to let you dev in HTTP
        # But it's ready for: return 301 https://$host$request_uri;
        
        location / {
            proxy_pass http://app;
        }

        location /api/ {
                proxy_pass http://api_gateway; 
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
}
