version: "3"

tasks:
  up:
    desc: "Run a service in development mode (Usage: task up | task up -- service_name)"
    cmds:
      - docker compose up {{.CLI_ARGS}}

  down:
    desc: "Stop and remove all containers"
    cmds:
      - docker compose down {{.CLI_ARGS}}

  prod:
    desc: "Run services in production mode"
    cmds:
      - docker compose {{.COMPOSE_PROD}} up --no-build -d vault
      - task vault:up
      - docker compose {{.COMPOSE_PROD}} up --no-build -d --force-recreate vault-agent-auth vault-agent-api-gateway vault-agent-user vault-agent-wiki vault-agent-net-gateway
      - docker compose {{.COMPOSE_PROD}} up --no-build {{.CLI_ARGS}} -d

  prod-build:
    desc: "Build production images"
    cmds:
      - docker compose {{.COMPOSE_PROD}} build {{.CLI_ARGS}}

  logs:
    desc: "Stream logs"
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  clean:
    desc: "Deep clean of containers and volumes"
    prompt: "Warning: This deletes ALL data. Continue?"
    cmds:
      - docker compose --profile dev --profile full down --rmi local --volumes --remove-orphans
      - rm -rf auth/vault/agent_ids api-gateway/vault/agent_ids user/vault/agent_ids wiki/vault/agent_ids net-gateway/vault/agent_ids
