syntax = "proto3";

package user;

service UserService {
  rpc GetUser (UserRequest) returns (UserResponse);
  rpc GetUserByUsername (UsernameRequest) returns (UserResponse);
  rpc GetUserByEmail (EmailRequest) returns (UserResponse);
  rpc CreateUser (CreateUserRequest) returns (UserResponse);
  rpc ListUsers (Empty) returns (UserListResponse);
  rpc DeleteUser (UserRequest) returns (UserResponse);
  rpc UpdateUser (UpdateUserRequest) returns (UserResponse);
  rpc AssignRole (RoleRequest) returns (UserResponse);
  rpc RemoveRole (RoleRequest) returns (UserResponse);
  rpc GetProfile (UserRequest) returns (ProfileResponse);
}

message Empty {}

message UsernameRequest {
  string username = 1;
}

message EmailRequest {
  string email = 1;
}

message RoleRequest {
  string user_id = 1;
  string role_id = 2;
}

message UserRequest {
  string    id = 1;
}

message UpdateUserRequest {
  string id = 1;
  optional string firstname = 2;
  optional string lastname = 3;
  optional string profile_picture = 4;
  optional bool   dark_theme = 5;
  optional string language = 6;
}

message CreateUserRequest {
  string    username = 1;
  string    firstname = 2;
  string    lastname = 3;
  string    email = 4;
}

message ProfileResponse {
  string id = 1;
  string profile_picture = 2;
  bool   dark_theme = 3;
  string language = 4;
}

message UserResponse {
  string    id = 1;
  string    username = 2;
  string    firstname = 3;
  string    lastname = 4;
  string    email = 5;
  ProfileResponse profile = 6;
  repeated string roles = 7;
  repeated string permissions = 8;
}

message UserListResponse {
  repeated UserResponse users = 1;
}
