---
- name: Check if already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join Cluster
  command: "{{ hostvars['master-01']['join_command_raw']['stdout'] }}"
  when: 
    - not kubelet_conf.stat.exists
    - hostvars['master-01']['join_command_raw'] is defined
  register: worker_join

- name: Ensure kubelet is running
  systemd:
    name: kubelet
    state: started
    enabled: yes
