---
- name: Common Configuration
  hosts: all
  become: yes
  roles:
    - common

- name: Setup Kubernetes Master
  hosts: master-01
  become: yes
  gather_facts: yes
  roles:
    - k8s-controller

- name: Setup Kubernetes Workers
  hosts: workers
  become: yes
  roles:
    - k8s-worker
